In [7]:
import numpy as np
import gym

# Initialize the Taxi-v3 environment
env = gym.make('Taxi-v3')

# Set the number of episodes for training
num_episodes = 10000

# Set the learning rate
alpha = 0.85

# Set the discount factor
gamma = 0.95

# Initialize the Q-table with zeros
Q = np.zeros([env.observation_space.n, env.action_space.n])

# Set the number of episodes for exploration
num_exploration_episodes = 1000

# Set the exploration rate
epsilon = 1.0

# Set the exploration decay rate
decay_rate = 0.001

# Set the minimum exploration rate
min_epsilon = 0.01

# Training loop
for episode in range(num_episodes):

    # Reset the environment
    state = env.reset()

    # Set the exploration rate for this episode
    if episode < num_exploration_episodes:
        epsilon = 1.0
    else:
        epsilon = min_epsilon + (1.0 - min_epsilon) * np.exp(-decay_rate * (episode - num_exploration_episodes))

    # Set the exploration flag
    exploration = np.random.uniform(0, 1) < epsilon

    # Training loop
    for step in range(1000):

        # Choose an action based on the exploration flag
        if exploration:
            action = env.action_space.sample()
        else:
            action = np.argmax(Q[state])

        # Take the action and get the next state and reward
        next_state, reward, done, info = env.step(action)

        # Update the Q-table
        Q[state, action] = (1 - alpha) * Q[state, action] + alpha * (reward + gamma * np.max(Q[next_state]))

        # Update the state
        state = next_state

        # Check if the episode is done
        if done:
            break

# Print the final Q-table
print(Q)

/usr/local/lib/python3.10/dist-packages/gym/core.py:317: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/usr/local/lib/python3.10/dist-packages/gym/wrappers/step_api_compatibility.py:39: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/usr/local/lib/python3.10/dist-packages/gym/utils/passive_env_checker.py:241: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):


[[ 0.          0.          0.          0.          0.          0.        ]
 [ 2.75200369  3.94947757  2.75200369  3.94947757  5.20997639 -5.05052243]
 [ 7.93349184  9.40367562  7.93349184  9.40367562 10.9512375   0.40367562]
 ...
 [10.9512375  12.58025    10.9512375   9.40367562  1.9512375   1.9512375 ]
 [ 5.20997639  6.53681725  5.20997639  6.53681725 -3.79002361 -3.79002361]
 [16.1        14.295      16.1        18.          7.1         7.1       ]]
